name: Build create-gecko-release action

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: none
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        shell: bash
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Configure git
        id: bot-config
        shell: bash
        run: |
          user_name="${{ steps.app-token.outputs.app-slug }}[bot]"
          user_email="${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          echo "user_name=$user_name" >> "$GITHUB_OUTPUT"
          echo "user_email=$user_email" >> "$GITHUB_OUTPUT"
          git config --global user.name $user_name
          git config --global user.email $user_email

      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}

      - shell: bash
        run: |
          echo ${{ github.run_id}} > run-id.txt

      - name: Commit changes
        id: commit
        uses: iarekylew00t/verified-bot-commit@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: |
            run-id.txt
          message: |
            ci: Test [skip ci]

            This is body

      - name: Create Tag
        shell: bash
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/git/tags \
            -f 'tag=test-tagging' \
            -f 'message="This is body"' \
            -f 'object=${{ steps.commit.outputs.commit }}' \
            -f 'type=commit' \
            -f 'tagger[name]=${{ steps.bot-config.outputs.user_name }}' \
            -f 'tagger[email]=${{ steps.bot-config.outputs.user_email }}' \
            -f 'tagger[date]=$(date --iso-8601=seconds)'

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/git/refs \
            -f 'ref=refs/tags/test-tagging' \
            -f 'sha=${{ steps.commit.outputs.commit }}'
